
version: '3.8'
services:
  web:
    build: .
    container_name: site_artigos_web
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./media:/app/media
      - ./data:/app/data
      - ./static:/app/static
    command: sh /app/entrypoint.sh
